version: '3.8' #docker-compose 버전 지정
services:
  redis:
    image: redis:latest
    container_name: redis
    ports:
      - "6379:6379"
  postgres:
    image: postgres:latest
    container_name: postgresSQL
    ports:
      - "5432:5432"
    environment:
      POSTGRES_DB: btrdb
      POSTGRES_USER: btuser
      POSTGRES_PASSWORD: 1016
  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:8.10.2 # elastic search 는 lastest version을 제공하지 않는다.
    container_name: elasticsearch
    ports:
      - "9200:9200"
      - "9300:9300"
    environment:
      discovery.type: single-node
  nginx:
    image: nginx:latest
    ports:
      - "80:80"
    volumes:
      - "./nginx.conf:/etc/nginx/nginx.conf:ro"
  jenkins:
    image: jenkins/jenkins:latest
    container_name: jenkins
    ports:
      - "8080:8080"  # HTTP
      - "8443:8443"  # HTTPS
      - "50000:50000"  # Jenkins slave
    volumes:
      - jenkins_home:/var/jenkins_home  # Jenkins 데이터 유지
      - /var/run/docker.sock:/var/run/docker.sock  # Docker API 연동
    environment:
      JAVA_OPTS: "-Djenkins.install.runSetupWizard=false" # 초기 설정 비활성화 (선택사황)
    networks:
      - jenkins_network
volumes:
  jenkins_home:

networks:
  jenkins_network:
    driver: bridge