spring:
  application:
    name: console-service
  datasource:
    url: jdbc:postgresql://localhost:5432/btrdb
    username: btuser
    password: 1016
    driver-class-name: org.postgresql.Driver
#  jpa:
#    hibernate:
#      ddl-auto: update # ?????? ?? ? ???? ???? ??/?????? ??
#    show-sql: true # SQL ??? ??? ???? ??
server:
  port: 9001
